### PR TITLE
explanation for commit "Makefile: Link libxml2 when building libxslt."

### PR DESCRIPTION
**Pull request by fallenworld**
I'm trying to build hangover on Linux. I got many "undefined reference to xml2XXXXX" errors when building libxslt-1.dll. More specificlly, it happens when executing "CCLD libexslt.la"(see build/libxslt64|32/libexslt/Makefile). Seems that many libxml2 functions are missing. Then I fixed it by adding libxml2 to Makefile and finnally successfully build it.

### CODE REVIEW

**Comment by fallenworld** [comment]
I try to build hangover without my patch. Yeah, the config.log shows that it found libxml:
```
configure:14559: checking for x86_64-w64-mingw32-xml2-config
configure:14592: result: no
configure:14602: checking for xml2-config
configure:14620: found /home/fallenworld/dev/tmp/hangover/build/x86_64-w64-mingw32/bin/xml2-config
configure:14632: result: /home/fallenworld/dev/tmp/hangover/build/x86_64-w64-mingw32/bin/xml2-config
 ...
 ...
LIBXML_CFLAGS='-I/home/fallenworld/dev/tmp/hangover/build/x86_64-w64-mingw32/include/libxml2 -I/home/fallenworld/dev/tmp/hangover/build/x86_64-w64-mingw32/include'
LIBXML_LIBS='-L/home/fallenworld/dev/tmp/hangover/build/x86_64-w64-mingw32/lib -lxml2
```

The "undefined reference to" errors happened when building **libexslt.dll** (it's libexslt, not libxslt).
Makefile builds it with commands below:
```
/bin/bash ../libtool --tag=CC  --mode=link x86_64-w64-mingw32-gcc  -I/home/fallenworld/dev/tmp/hangover/build/x86_64-w64-mingw32/include/libxml2 -I/home/fallenworld/dev/tmp/hangover/build/x86_64-w64-mingw32/include -g -O2 -Wall -Wformat=2 -Wmissing-format-attribute -no-undefined -version-info 8:20:8  -o libexslt.la -rpath /home/fallenworld/dev/tmp/hangover/build/x86_64-w64-mingw32/lib exslt.lo common.lo crypto.lo math.lo sets.lo functions.lo strings.lo date.lo saxon.lo dynamic.lo ../libxslt/libxslt.la    
libtool: link: rm -fr  .libs/libexslt.dll.a
libtool: link: x86_64-w64-mingw32-gcc -shared  .libs/exslt.o .libs/common.o .libs/crypto.o .libs/math.o .libs/sets.o .libs/functions.o .libs/strings.o .libs/date.o .libs/saxon.o .libs/dynamic.o   ../libxslt/.libs/libxslt.dll.a -L/home/fallenworld/dev/tmp/hangover/build/x86_64-w64-mingw32/lib  -g -O2   -o .libs/libexslt-0.dll -Wl,--enable-auto-image-base -Xlinker --out-implib -Xlinker .libs/libexslt.dll.a
```
Check out the third line. It doesn't link libxml2 when linking all object files together to generate libexslt-0.dll. However, it links libxslt.dll.a (../libxslt/.libs/libxslt.dll.a). Seems that libxslt.dll.a should contains xml2 functions. So I tried this:
```
cd hangover/build/libxslt64/libxslt/.libs
nm libxslt.dll.a
```
However, the result shows that libxslt.dll.a doesn't have xml2 functions that libexslt.dll needs. Then I tried to find out how libxslt.dll.a is build:
```
/bin/bash ../libtool --tag=CC --mode=link x86_64-w64-mingw32-gcc -I/home/fallenworld/dev/codeweavers/hangover/build/x86_64-w64-mingw32/include/libxml2 -I/home/fallenworld/dev/codeweavers/hangover/build/x86_64-w64-mingw32/include -g -O2 -Wall -Wformat=2 -Wmissing-format-attribute -no-undefined -Wl,--version-script=../../../libxslt/libxslt/libxslt.syms -version-info 2:32:1 -L/home/fallenworld/dev/codeweavers/hangover/build/x86_64-w64-mingw32/lib -o libxslt.la -rpath /home/fallenworld/dev/codeweavers/hangover/build/x86_64-w64-mingw32/lib attrvt.lo xslt.lo xsltlocale.lo xsltutils.lo pattern.lo templates.lo variables.lo keys.lo numbers.lo extensions.lo extra.lo functions.lo namespaces.lo imports.lo attributes.lo documents.lo preproc.lo transform.lo security.lo  -L/home/fallenworld/dev/codeweavers/hangover/build/x86_64-w64-mingw32/lib -lxml2   -lxml2
libtool: link: x86_64-w64-mingw32-gcc -shared  .libs/attrvt.o .libs/xslt.o .libs/xsltlocale.o .libs/xsltutils.o .libs/pattern.o .libs/templates.o .libs/variables.o .libs/keys.o .libs/numbers.o .libs/extensions.o .libs/extra.o .libs/functions.o .libs/namespaces.o .libs/imports.o .libs/attributes.o .libs/documents.o .libs/preproc.o .libs/transform.o .libs/security.o   -L/home/fallenworld/dev/codeweavers/hangover/build/x86_64-w64-mingw32/lib /home/fallenworld/dev/codeweavers/hangover/build/x86_64-w64-mingw32/lib/libxml2.dll.a  -g -O2 -Wl,--version-script=../../../libxslt/libxslt/libxslt.syms   -o .libs/libxslt-1.dll -Wl,--enable-auto-image-base -Xlinker --out-implib -Xlinker .libs/libxslt.dll.a
```
The second line contains "/home/fallenworld/dev/codeweavers/hangover/build/x86_64-w64-mingw32/lib/libxml2.dll.a". So it links libxml2.dll.a when building libxslt-1.dll. Then I tried "nm libxslt-1.dll". The result shows that libxslt-1.dll does contain xml2 functions. However, libxslt.dll.a doesn't. That's weird.

So here is the points:

- libexslt.dll relies on xml2 functions
- libexslt.dll doesn't link libxml2
- libexslt.dll links libxslt.dll.a
- libxslt.dll.a doesn't contain xml2 functions
- libxslt.dll links libxml2, and libxslt.dll have xml2 functions.
- What is weird is, libxslt.dll contains xml2 functions while libxslt.dll.a doesn't
- This problem can be solved by linking libxml2 when building libexslt.dll. That is what my patch do.

**Comment by stefand** [comment]
It is weird though that my mingw figures it out OK.  Can you see if you can get a newer version for your Linux distro?

This is what I am running here:

stefan@shield ~ $ i686-w64-mingw32-gcc --version
i686-w64-mingw32-gcc (Gentoo 8.2.0-r3 p1.3) 8.2.0

stefan@shield ~ $ i686-w64-mingw32-ld --version
GNU ld (Gentoo 2.31.1 p3) 2.31.1
Copyright (C) 2018 Free Software Foundation, Inc.

Re the other patch, one minor thing I noticed when I tried to cherry-pick it: Can you set your real name as the author information on it?

**Comment by fallenworld** [comment]
alright, I'll open a new pull request and use my real name

**Comment by kokcola** [comment]
I have the same error. What code should I change? Please Help!!

**Comment by ziqingh** [comment]
> I have the same error. What code should I change? Please Help!!
It can be fixed by: [](https://github.com/ziqingh/hangover/commit/665341fc667ea7474574cd2effa784dd46669360)

@stefand It seems that someone else got the same error as me. Should we apply the patch above so that we can avoid more people getting the same error? I believe that this error will happen on Debian based system, including Raspbian. I tried building on my Raspberry 4 device, and got this error. I think there will be many people building hangover on Raspberry, so it would be good to fix this.

**Pull request closed without merging**
