### PR TITLE
CI

### PR DESCRIPTION
**Pull request by Trass3r**
Tested Github Actions CI but it just won't compile: https://github.com/Trass3r/hangover/actions

### CODE REVIEW

**Comment by AndreRH** [comment]
Could you provide logs?

**Comment by Trass3r** [comment]
You don't have access to them? https://github.com/Trass3r/hangover/actions

**Comment by AndreRH** [comment]
yes, I was confused where to click, got it now...
Could you try rebasing your patches on top of hangover-0.4.0 and see if it builds please?

**Comment by Trass3r** [comment]
I don't see any new changes on your master. Everything's up-to-date.

**Comment by AndreRH** [comment]
i don't mean master, I mean the tag called "hangover-0.4.0"

**Comment by Trass3r** [comment]
https://github.com/Trass3r/hangover/runs/438418361

**Comment by AndreRH** [comment]
might be related to the changed ndk version...

**Comment by Trass3r** [comment]
I only changed that later. Early attempts failed too: https://github.com/Trass3r/hangover/runs/394161054

**Comment by AndreRH** [comment]
I did a quick try: https://github.com/AndreRH/hangover-ci/actions
just noticed I need to update the reference to Notepad++

**Comment by Trass3r** [comment]
Looks like it doesn't always build for you either.

**Comment by AndreRH** [comment]
I finally made it, thx for your inspiration and improvements are still welcome!

**Comment by Trass3r** [comment]
Glad it helped. I guess what's still missing is uploading the apk as an artifact.

**Pull request closed without merging**
