### PR TITLE
Makefile: Also set HANGOVER_WINE_CC/HANGOVER_WINE_CXX for Wine tools compilation process.

### PR DESCRIPTION
**Pull request by jzengc**
Tested on Debian bullseye ARM64 with both gcc and clang installed.

### CODE REVIEW

**Comment by AndreRH** [comment]
Hi and thanks for the patch,
but I'm afraid it's not that easy. This change would break crosscompiling, for example:
https://github.com/AndreRH/hangover/blob/hangover-0.5.15/Dockerfile.cross_ppc64le#L47


PS: I activated Github actions for pull requests now, that way it get's obvious next time

**Comment by cwabbott0** [comment]
What would a "proper" solution look like? I had to do this exact same thing...

**Comment by AndreRH** [comment]
I meanwhile committed 25651b3008812c08161c1615247dac8934d96fab
That hopefully should do the trick

**Comment by jzengc** [comment]
Hi Andre,
> I meanwhile committed [25651b3](https://github.com/AndreRH/hangover/commit/25651b3008812c08161c1615247dac8934d96fab)
> That hopefully should do the trick

It looks like this doesn't work for my case. The issue I met is that gcc was selected by default for the Wine tools build process while both gcc and clang are installed, but gcc doesn't support __builtin_ms_va_list on Debian ARM64.
I don't know why my hack broke the PPC64 building, still didn't try it.  Probably introducing a new environment variable for the Wine tools build process will make both Debian ARM64 and PPC64 happy ;-), but sure, this quite tricky, and I think will be better to avoid.

**Comment by AndreRH** [comment]
> I don't know why my hack broke the PPC64 building, still didn't try it. Probably introducing a new environment variable for the Wine tools build process will make both Debian ARM64 and PPC64 happy ;-), but sure, this quite tricky, and I think will be better to avoid.

I just went ahead and did that, so please try as of d43f8e0fae368fcdbf68f364e76e7bb5c25e5fe7

**Comment by jzengc** [comment]
> > I don't know why my hack broke the PPC64 building, still didn't try it. Probably introducing a new environment variable for the Wine tools build process will make both Debian ARM64 and PPC64 happy ;-), but sure, this quite tricky, and I think will be better to avoid.
> 
> I just went ahead and did that, so please try as of [d43f8e0](https://github.com/AndreRH/hangover/commit/d43f8e0fae368fcdbf68f364e76e7bb5c25e5fe7)

Yes, this works for me. Thanks!

**Pull request closed without merging**
